FROM ubuntu:20.04

ARG USERNAME=robot
ARG USER_UID=1000
ARG USER_GID=$USER_UID
ARG PWD=./
WORKDIR $PWD

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME \
    && apt-get install -y git \
USER ${USERNAME}
ENV USER=${USERNAME}
ENV LANG=en_US.UTF-8